modLoader="javafml" #mandatory
license="MIT (https://github.com/luigiDB/redStoneExperience/blob/master/LICENSE.md)"
loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="https://github.com/luigiDB/redStoneExperience/issues" #optional

[[mods]] #mandatory
modId="redstoneexperience" #mandatory
version="${file.jarVersion}" #mandatory
displayName="RedStone Experience" #mandatory
updateJSONURL="https://github.com/luigiDB/redStoneExperience/raw/master/update.json" #optional
displayURL="http://example.com/" #optional
logoFile="redstoneexperience_logo.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="luigiDB" #optional
description='''
A mod to enable smarter redstone control.
'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
